version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.oauth2
    ports:
      - "80:80"  # Expose port 80 for HTTP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - anothernetwork 
  
networks:
    anothernetwork: {}
