version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expose port 80 for HTTP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - my_network

  # test:
  #   image: "ubuntu:latest"
  #   networks:
  #     - my_network  
  #   tty: true  
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"    
networks:
  my_network: